---

name: Build OpenTelemetry Collector Lambda distribution
on:
  workflow_dispatch:
    inputs:
      repository:
        description: OpenTelemetry collector repository (OWNER/REPO)
        type: string
        default: aereal/opentelemetry-lambda
      ref:
        description: commit reference to be built
        type: string
        default: own-dist
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
      - id: determine_hash
        run: |
          echo "commit_hash=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
      - run: |
          echo "# Build $repo" >> "$GITHUB_STEP_SUMMARY"
          echo >> "$GITHUB_STEP_SUMMARY"
          echo "- ref: `$commit_ref`" >> "$GITHUB_STEP_SUMMARY"
          echo "- commit hash: `$commit_hash`" >> "$GITHUB_STEP_SUMMARY"
        env:
          repo: ${{ inputs.repository }}
          commit_ref: ${{ inputs.ref }}
          commit_hash: ${{ steps.determine_hash.outputs.commit_hash }}
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.work'
      - run: go work sync
      - name: build
        run: make package
        working-directory: ./collector
